debug_mode = false

[server]
host = "0.0.0.0"
port = 8080

[database]
type = "postgres"
username = "admin"
password = "secret"
endpoint = "localhost:5432"

[gateway]
metrics_enabled = true
[gateway.publisher]
type = "kafka"
brokers = ["127.0.0.1:9092"]
compression = "none"
client_id = "event-gateway"
acks = -1
retries = 3
required_acks = "none"
conn_idle_timeout = "5m"
message_timeout = "5s"
ack_timeout = "5s"
metadata_field_as_key = "user_id"

[api]
prefix = "/api/v1"
[api.jwt_auth]
jwks_url = "https://samples.auth0.com/.well-known/jwks.json"
refresh_interval_secs = 300 