version: "3.8"

services:
  redpanda:
    image: vectorized/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --node-id
      - "0"
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --check=true
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      - REDPANDA_AUTO_CREATE_TOPICS=true
    healthcheck:
      test: ["CMD", "rpk", "cluster", "health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    depends_on:
      redpanda:
        condition: service_healthy
    ports:
      - "8089:8080"
    environment:
      - KAFKA_BROKERS=redpanda:29092
      - SERVER_LISTENADDRESS=0.0.0.0
      - SERVER_LISTENPORT=8080

networks:
  default:
    name: kafka-network
